# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(430, 730)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("STE.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 388, 238))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_tracks = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.widget_tracks.setObjectName("widget_tracks")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_tracks)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3.addWidget(self.widget_tracks)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 2)
        self.spinBox_first = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_first.setEnabled(False)
        self.spinBox_first.setMinimum(1)
        self.spinBox_first.setObjectName("spinBox_first")
        self.gridLayout_3.addWidget(self.spinBox_first, 1, 0, 1, 1)
        self.spinBox_second = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_second.setEnabled(False)
        self.spinBox_second.setMinimum(1)
        self.spinBox_second.setObjectName("spinBox_second")
        self.gridLayout_3.addWidget(self.spinBox_second, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_gp5 = QtWidgets.QPushButton(self.widget)
        self.button_gp5.setEnabled(False)
        self.button_gp5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_gp5.setCheckable(False)
        self.button_gp5.setChecked(False)
        self.button_gp5.setAutoExclusive(False)
        self.button_gp5.setAutoDefault(False)
        self.button_gp5.setDefault(False)
        self.button_gp5.setFlat(False)
        self.button_gp5.setObjectName("button_gp5")
        self.horizontalLayout.addWidget(self.button_gp5)
        self.button_midi = QtWidgets.QPushButton(self.widget)
        self.button_midi.setEnabled(False)
        self.button_midi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_midi.setObjectName("button_midi")
        self.horizontalLayout.addWidget(self.button_midi)
        self.gridLayout_3.addWidget(self.widget, 2, 0, 1, 2)
        self.button_external_editor = QtWidgets.QPushButton(self.widget_2)
        self.button_external_editor.setEnabled(False)
        self.button_external_editor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_external_editor.setObjectName("button_external_editor")
        self.gridLayout_3.addWidget(self.button_external_editor, 3, 0, 2, 2)
        self.verticalLayout.addWidget(self.widget_2)
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.button_select = QtWidgets.QPushButton(self.centralwidget)
        self.button_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_select.setObjectName("button_select")
        self.gridLayout.addWidget(self.button_select, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 170))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 388, 125))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_info = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_info.setText("")
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.horizontalLayout_2.addWidget(self.label_info)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 2)
        self.button_ok = QtWidgets.QPushButton(self.centralwidget)
        self.button_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_ok.setStatusTip("")
        self.button_ok.setWhatsThis("")
        self.button_ok.setAutoDefault(False)
        self.button_ok.setDefault(False)
        self.button_ok.setFlat(False)
        self.button_ok.setObjectName("button_ok")
        self.gridLayout.addWidget(self.button_ok, 1, 0, 1, 2)
        self.lineEdit_location = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_location.setInputMask("")
        self.lineEdit_location.setText("")
        self.lineEdit_location.setObjectName("lineEdit_location")
        self.gridLayout.addWidget(self.lineEdit_location, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionPolish = QtWidgets.QAction(MainWindow)
        self.actionPolish.setObjectName("actionPolish")
        self.action_open_in_external_editor = QtWidgets.QAction(MainWindow)
        self.action_open_in_external_editor.setEnabled(False)
        self.action_open_in_external_editor.setObjectName("action_open_in_external_editor")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Tablature Editor "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Select tracks"))
        self.label_2.setText(_translate("MainWindow", "Choose measures"))
        self.button_gp5.setToolTip(_translate("MainWindow", "Save as GuitarPro 5 file (Ctrl + S)"))
        self.button_gp5.setText(_translate("MainWindow", "Save as GP5"))
        self.button_gp5.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.button_midi.setToolTip(_translate("MainWindow", "Save as MIDI file (Ctrl + M)"))
        self.button_midi.setText(_translate("MainWindow", "Save as MIDI"))
        self.button_midi.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.button_external_editor.setToolTip(_translate("MainWindow", "Open in an external editor that you have installed (Ctrl + E)"))
        self.button_external_editor.setText(_translate("MainWindow", "Open in external editor"))
        self.button_external_editor.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.button_select.setToolTip(_translate("MainWindow", "Select a file from your computer "))
        self.button_select.setText(_translate("MainWindow", "Select file"))
        self.groupBox.setTitle(_translate("MainWindow", "Song information"))
        self.button_ok.setToolTip(_translate("MainWindow", "Load Song (Enter)"))
        self.button_ok.setText(_translate("MainWindow", "Load Song"))
        self.button_ok.setShortcut(_translate("MainWindow", "Return"))
        self.lineEdit_location.setPlaceholderText(_translate("MainWindow", "Select file or type URL"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
        self.actionPolish.setText(_translate("MainWindow", "Polish"))
        self.action_open_in_external_editor.setText(_translate("MainWindow", "Open in external Editor"))
        self.action_open_in_external_editor.setShortcut(_translate("MainWindow", "Ctrl+E"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
